// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Penuel.Infrastructure.Persistence;

#nullable disable

namespace Penuel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260828153341_AddDeveloperRole")]
    partial class AddDeveloperRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Penuel.Domain.Entities.Church", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("integer")
                        .HasColumnName("founded_year");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.HasKey("Id")
                        .HasName("pk_churches");

                    b.ToTable("churches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000000000001"),
                            Address = "Manzana 8, Lote 2, Calle Enrique Higuera M, S/N, C.P. 87270, Colonia Ejido Loma Alta, Ciudad Victoria, Tamaulipas",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FoundedYear = 1997,
                            Name = "Comunidad Cristiana Penuel",
                            TimeZone = "America/Mexico_City"
                        });
                });

            modelBuilder.Entity("Penuel.Domain.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid")
                        .HasColumnName("church_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("JoinedAt")
                        .HasColumnType("date")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid?>("RegisteredByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("registered_by_person_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_memberships");

                    b.HasIndex("ChurchId")
                        .HasDatabaseName("ix_memberships_church_id");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_memberships_person_id");

                    b.HasIndex("RegisteredByPersonId")
                        .HasDatabaseName("ix_memberships_registered_by_person_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_memberships_status");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("Penuel.Domain.Entities.Ministry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid")
                        .HasColumnName("church_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_ministries");

                    b.HasIndex("ChurchId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_ministries_church_id_name");

                    b.ToTable("ministries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-4000-8000-000000000001"),
                            ChurchId = new Guid("10000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Campañas, evangelismo casa por casa y el proyecto UNO+UNO.",
                            Name = "Evangelismo"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-4000-8000-000000000002"),
                            ChurchId = new Guid("10000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Organiza los cultos, recibe a los visitantes y tiene bajo su cuidado a las Sociedades de Damas, Varones y Jóvenes.",
                            Name = "Comunión"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-4000-8000-000000000003"),
                            ChurchId = new Guid("10000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Escuela Bíblica Local y cursos de Catecúmenos, Prebautismal y Prematrimonial.",
                            Name = "Discipulado"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-4000-8000-000000000004"),
                            ChurchId = new Guid("10000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Grupos de alabanza, vida devocional y la agenda de veladas y vigilias.",
                            Name = "Adoración"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-4000-8000-000000000005"),
                            ChurchId = new Guid("10000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Ujieres, eventos especiales, ACUPYHNAD y mantenimiento de los bienes.",
                            Name = "Servicio"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-4000-8000-000000000006"),
                            ChurchId = new Guid("10000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Atiende a los niños de la congregación. Ministerio propio e independiente, con encargado propio igual que los otros cinco.",
                            Name = "Ministerio Infantil"
                        });
                });

            modelBuilder.Entity("Penuel.Domain.Entities.MinistryLeadership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_person_id");

                    b.Property<Guid>("MinistryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ministry_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_person_id");

                    b.HasKey("Id")
                        .HasName("pk_ministry_leaderships");

                    b.HasIndex("AssignedByPersonId")
                        .HasDatabaseName("ix_ministry_leaderships_assigned_by_person_id");

                    b.HasIndex("MinistryId")
                        .IsUnique()
                        .HasDatabaseName("ux_ministry_leaderships_active")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("RevokedByPersonId")
                        .HasDatabaseName("ix_ministry_leaderships_revoked_by_person_id");

                    b.HasIndex("PersonId", "RevokedAt")
                        .HasDatabaseName("ix_ministry_leaderships_person_id_revoked_at");

                    b.ToTable("ministry_leaderships", (string)null);
                });

            modelBuilder.Entity("Penuel.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid")
                        .HasColumnName("church_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_person_id");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_person_id");

                    b.HasKey("Id")
                        .HasName("pk_persons");

                    b.HasIndex("ChurchId")
                        .HasDatabaseName("ix_persons_church_id");

                    b.HasIndex("CreatedByPersonId")
                        .HasDatabaseName("ix_persons_created_by_person_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_persons_status");

                    b.HasIndex("UpdatedByPersonId")
                        .HasDatabaseName("ix_persons_updated_by_person_id");

                    b.HasIndex("LastName", "FirstName")
                        .HasDatabaseName("ix_persons_last_name_first_name");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("Penuel.Domain.Entities.PersonPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_person_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_person_id");

                    b.HasKey("Id")
                        .HasName("pk_person_positions");

                    b.HasIndex("AssignedByPersonId")
                        .HasDatabaseName("ix_person_positions_assigned_by_person_id");

                    b.HasIndex("RevokedByPersonId")
                        .HasDatabaseName("ix_person_positions_revoked_by_person_id");

                    b.HasIndex("PersonId", "RevokedAt")
                        .HasDatabaseName("ix_person_positions_person_id_revoked_at");

                    b.HasIndex("PositionId", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("ux_person_positions_active")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("person_positions", (string)null);
                });

            modelBuilder.Entity("Penuel.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid")
                        .HasColumnName("church_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsExecutiveBody")
                        .HasColumnType("boolean")
                        .HasColumnName("is_executive_body");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.HasIndex("IsExecutiveBody")
                        .HasDatabaseName("ix_positions_is_executive_body");

                    b.HasIndex("ChurchId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_positions_church_id_name");

                    b.ToTable("positions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-4000-8000-000000000001"),
                            ChurchId = new Guid("10000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Máxima autoridad. Preside la Asamblea General de miembros y el Cuerpo Ejecutivo.",
                            IsExecutiveBody = true,
                            Name = "Pastor"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-4000-8000-000000000002"),
                            ChurchId = new Guid("10000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Oficio eclesiástico. Admite varios titulares activos a la vez (Sección 6.13).",
                            IsExecutiveBody = true,
                            Name = "Diácono"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-4000-8000-000000000003"),
                            ChurchId = new Guid("10000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Registros y actas de la iglesia. Integra el Cuerpo Ejecutivo.",
                            IsExecutiveBody = true,
                            Name = "Secretario General"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-4000-8000-000000000004"),
                            ChurchId = new Guid("10000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Administra la Ofrenda. El registro y control de los Diezmos corresponde directamente al Pastor (regla 7.12).",
                            IsExecutiveBody = true,
                            Name = "Tesorero General"
                        });
                });

            modelBuilder.Entity("Penuel.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_token_hash");

                    b.HasIndex("UserAccountId", "RevokedAt")
                        .HasDatabaseName("ix_refresh_tokens_user_account_id_revoked_at");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Penuel.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid")
                        .HasColumnName("church_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("ChurchId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_church_id_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-4000-8000-000000000001"),
                            ChurchId = new Guid("10000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Control total del sistema: gestiona personas, membresías, roles, ministerios, sociedades y cargos.",
                            IsSystemRole = true,
                            Name = "Pastor"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-4000-8000-000000000002"),
                            ChurchId = new Guid("10000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Puede levantar y corregir los reportes de Escuela Dominical de cualquier grupo. No implica ser maestro de ninguno.",
                            IsSystemRole = true,
                            Name = "SundaySchoolRecorder"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-4000-8000-000000000003"),
                            ChurchId = new Guid("10000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Acceso irrestricto para el mantenimiento técnico del sistema. No es un cargo de la iglesia y no implica membresía ni liderazgo.",
                            IsSystemRole = true,
                            Name = "Desarrollador"
                        });
                });

            modelBuilder.Entity("Penuel.Domain.Entities.Services.ServiceAttendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("BroughtBible")
                        .HasColumnType("boolean")
                        .HasColumnName("brought_bible");

                    b.Property<int?>("ChaptersRead")
                        .HasColumnType("integer")
                        .HasColumnName("chapters_read");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("ServiceSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_session_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_person_id");

                    b.Property<bool>("WasPresent")
                        .HasColumnType("boolean")
                        .HasColumnName("was_present");

                    b.Property<bool?>("WasPunctual")
                        .HasColumnType("boolean")
                        .HasColumnName("was_punctual");

                    b.HasKey("Id")
                        .HasName("pk_service_attendances");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_service_attendances_person_id");

                    b.HasIndex("UpdatedByPersonId")
                        .HasDatabaseName("ix_service_attendances_updated_by_person_id");

                    b.HasIndex("ServiceSessionId", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("ux_service_attendances_session_person");

                    b.ToTable("service_attendances", (string)null);
                });

            modelBuilder.Entity("Penuel.Domain.Entities.Services.ServiceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_person_id");

                    b.Property<Guid?>("PreacherPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("preacher_person_id");

                    b.Property<Guid>("ServiceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_type_id");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date")
                        .HasColumnName("session_date");

                    b.Property<Guid?>("SocietyId")
                        .HasColumnType("uuid")
                        .HasColumnName("society_id");

                    b.Property<Guid?>("TeacherPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_person_id");

                    b.Property<decimal>("TotalOffering")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_offering");

                    b.Property<decimal?>("TotalTithe")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_tithe");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_person_id");

                    b.HasKey("Id")
                        .HasName("pk_service_sessions");

                    b.HasIndex("CreatedByPersonId")
                        .HasDatabaseName("ix_service_sessions_created_by_person_id");

                    b.HasIndex("PreacherPersonId")
                        .HasDatabaseName("ix_service_sessions_preacher_person_id");

                    b.HasIndex("SessionDate")
                        .HasDatabaseName("ix_service_sessions_session_date");

                    b.HasIndex("SocietyId")
                        .HasDatabaseName("ix_service_sessions_society_id");

                    b.HasIndex("TeacherPersonId")
                        .HasDatabaseName("ix_service_sessions_teacher_person_id");

                    b.HasIndex("UpdatedByPersonId")
                        .HasDatabaseName("ix_service_sessions_updated_by_person_id");

                    b.HasIndex("ServiceTypeId", "SessionDate")
                        .IsUnique()
                        .HasDatabaseName("ux_service_sessions_without_society")
                        .HasFilter("society_id IS NULL");

                    b.HasIndex("ServiceTypeId", "SessionDate", "SocietyId")
                        .IsUnique()
                        .HasDatabaseName("ux_service_sessions_by_society")
                        .HasFilter("society_id IS NOT NULL");

                    b.ToTable("service_sessions", (string)null);
                });

            modelBuilder.Entity("Penuel.Domain.Entities.Services.ServiceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AttendanceCustomary")
                        .HasColumnType("boolean")
                        .HasColumnName("attendance_customary");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid")
                        .HasColumnName("church_id");

                    b.Property<bool>("CollectsTithe")
                        .HasColumnType("boolean")
                        .HasColumnName("collects_tithe");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresSocietyGrouping")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_society_grouping");

                    b.HasKey("Id")
                        .HasName("pk_service_types");

                    b.HasIndex("ChurchId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_service_types_church_id_name");

                    b.ToTable("service_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("60000000-0000-4000-8000-000000000001"),
                            AttendanceCustomary = true,
                            ChurchId = new Guid("10000000-0000-4000-8000-000000000001"),
                            CollectsTithe = false,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Escuela Dominical",
                            RequiresSocietyGrouping = true
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-4000-8000-000000000002"),
                            AttendanceCustomary = false,
                            ChurchId = new Guid("10000000-0000-4000-8000-000000000001"),
                            CollectsTithe = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Culto General",
                            RequiresSocietyGrouping = false
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-4000-8000-000000000003"),
                            AttendanceCustomary = false,
                            ChurchId = new Guid("10000000-0000-4000-8000-000000000001"),
                            CollectsTithe = false,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Culto de Oración",
                            RequiresSocietyGrouping = false
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-4000-8000-000000000004"),
                            AttendanceCustomary = false,
                            ChurchId = new Guid("10000000-0000-4000-8000-000000000001"),
                            CollectsTithe = false,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Culto de Jóvenes",
                            RequiresSocietyGrouping = false
                        });
                });

            modelBuilder.Entity("Penuel.Domain.Entities.Services.SundaySchoolTeachingAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_person_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_person_id");

                    b.Property<Guid?>("SocietyId")
                        .HasColumnType("uuid")
                        .HasColumnName("society_id");

                    b.HasKey("Id")
                        .HasName("pk_sunday_school_teaching_assignments");

                    b.HasIndex("AssignedByPersonId")
                        .HasDatabaseName("ix_sunday_school_teaching_assignments_assigned_by_person_id");

                    b.HasIndex("RevokedByPersonId")
                        .HasDatabaseName("ix_sunday_school_teaching_assignments_revoked_by_person_id");

                    b.HasIndex("PersonId", "RevokedAt")
                        .HasDatabaseName("ix_sunday_school_teaching_assignments_person_id_revoked_at");

                    b.HasIndex("SocietyId", "RevokedAt")
                        .HasDatabaseName("ix_sunday_school_teaching_assignments_society_id_revoked_at");

                    b.ToTable("sunday_school_teaching_assignments", (string)null);
                });

            modelBuilder.Entity("Penuel.Domain.Entities.Services.TitheEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_person_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("ServiceSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_session_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_person_id");

                    b.HasKey("Id")
                        .HasName("pk_tithe_entries");

                    b.HasIndex("CreatedByPersonId")
                        .HasDatabaseName("ix_tithe_entries_created_by_person_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_tithe_entries_person_id");

                    b.HasIndex("UpdatedByPersonId")
                        .HasDatabaseName("ix_tithe_entries_updated_by_person_id");

                    b.HasIndex("ServiceSessionId", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("ux_tithe_entries_session_person");

                    b.ToTable("tithe_entries", (string)null);
                });

            modelBuilder.Entity("Penuel.Domain.Entities.Society", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid")
                        .HasColumnName("church_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_societies");

                    b.HasIndex("ChurchId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_societies_church_id_name");

                    b.ToTable("societies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-4000-8000-000000000001"),
                            ChurchId = new Guid("10000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Bajo el cuidado general del Ministerio de Comunión.",
                            Name = "Damas"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-4000-8000-000000000002"),
                            ChurchId = new Guid("10000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Bajo el cuidado general del Ministerio de Comunión.",
                            Name = "Varones"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-4000-8000-000000000003"),
                            ChurchId = new Guid("10000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Bajo el cuidado general del Ministerio de Comunión.",
                            Name = "Jóvenes"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-4000-8000-000000000004"),
                            ChurchId = new Guid("10000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Agrupa a los niños de la congregación. Complementa al Ministerio Infantil sin duplicarlo: son dos registros distintos. El ministerio es el departamento funcional con su encargado; esta sociedad existe para agrupar la asistencia igual que Damas, Varones y Jóvenes.",
                            Name = "Infantil"
                        });
                });

            modelBuilder.Entity("Penuel.Domain.Entities.SocietyLeadership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_person_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_person_id");

                    b.Property<Guid>("SocietyId")
                        .HasColumnType("uuid")
                        .HasColumnName("society_id");

                    b.HasKey("Id")
                        .HasName("pk_society_leaderships");

                    b.HasIndex("AssignedByPersonId")
                        .HasDatabaseName("ix_society_leaderships_assigned_by_person_id");

                    b.HasIndex("RevokedByPersonId")
                        .HasDatabaseName("ix_society_leaderships_revoked_by_person_id");

                    b.HasIndex("SocietyId")
                        .IsUnique()
                        .HasDatabaseName("ux_society_leaderships_active")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("PersonId", "RevokedAt")
                        .HasDatabaseName("ix_society_leaderships_person_id_revoked_at");

                    b.ToTable("society_leaderships", (string)null);
                });

            modelBuilder.Entity("Penuel.Domain.Entities.SocietyMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_person_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_person_id");

                    b.Property<Guid>("SocietyId")
                        .HasColumnType("uuid")
                        .HasColumnName("society_id");

                    b.HasKey("Id")
                        .HasName("pk_society_memberships");

                    b.HasIndex("AssignedByPersonId")
                        .HasDatabaseName("ix_society_memberships_assigned_by_person_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_society_memberships_person_id");

                    b.HasIndex("RevokedByPersonId")
                        .HasDatabaseName("ix_society_memberships_revoked_by_person_id");

                    b.HasIndex("SocietyId", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("ux_society_memberships_active")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("SocietyId", "RevokedAt")
                        .HasDatabaseName("ix_society_memberships_society_id_revoked_at");

                    b.ToTable("society_memberships", (string)null);
                });

            modelBuilder.Entity("Penuel.Domain.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user_accounts");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_user_accounts_email");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_accounts_person_id");

                    b.ToTable("user_accounts", (string)null);
                });

            modelBuilder.Entity("Penuel.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_person_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_person_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id")
                        .HasName("pk_user_roles");

                    b.HasIndex("AssignedByPersonId")
                        .HasDatabaseName("ix_user_roles_assigned_by_person_id");

                    b.HasIndex("RevokedByPersonId")
                        .HasDatabaseName("ix_user_roles_revoked_by_person_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.HasIndex("UserAccountId", "RevokedAt")
                        .HasDatabaseName("ix_user_roles_user_account_id_revoked_at");

                    b.HasIndex("UserAccountId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_roles_active")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Penuel.Domain.Entities.Membership", b =>
                {
                    b.HasOne("Penuel.Domain.Entities.Church", null)
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_churches_church_id");

                    b.HasOne("Penuel.Domain.Entities.Person", "Person")
                        .WithOne()
                        .HasForeignKey("Penuel.Domain.Entities.Membership", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_persons_person_id");

                    b.HasOne("Penuel.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("RegisteredByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_memberships_persons_registered_by_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Penuel.Domain.Entities.Ministry", b =>
                {
                    b.HasOne("Penuel.Domain.Entities.Church", null)
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ministries_churches_church_id");
                });

            modelBuilder.Entity("Penuel.Domain.Entities.MinistryLeadership", b =>
                {
                    b.HasOne("Penuel.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("AssignedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ministry_leaderships_persons_assigned_by_person_id");

                    b.HasOne("Penuel.Domain.Entities.Ministry", "Ministry")
                        .WithMany()
                        .HasForeignKey("MinistryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ministry_leaderships_ministries_ministry_id");

                    b.HasOne("Penuel.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ministry_leaderships_persons_person_id");

                    b.HasOne("Penuel.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("RevokedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ministry_leaderships_persons_revoked_by_person_id");

                    b.Navigation("Ministry");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Penuel.Domain.Entities.Person", b =>
                {
                    b.HasOne("Penuel.Domain.Entities.Church", null)
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_persons_churches_church_id");

                    b.HasOne("Penuel.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("CreatedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_persons_persons_created_by_person_id");

                    b.HasOne("Penuel.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_persons_persons_updated_by_person_id");
                });

            modelBuilder.Entity("Penuel.Domain.Entities.PersonPosition", b =>
                {
                    b.HasOne("Penuel.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("AssignedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_person_positions_persons_assigned_by_person_id");

                    b.HasOne("Penuel.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_person_positions_persons_person_id");

                    b.HasOne("Penuel.Domain.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_person_positions_positions_position_id");

                    b.HasOne("Penuel.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("RevokedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_person_positions_persons_revoked_by_person_id");

                    b.Navigation("Person");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Penuel.Domain.Entities.Position", b =>
                {
                    b.HasOne("Penuel.Domain.Entities.Church", null)
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_positions_churches_church_id");
                });

            modelBuilder.Entity("Penuel.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Penuel.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_user_accounts_user_account_id");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Penuel.Domain.Entities.Role", b =>
                {
                    b.HasOne("Penuel.Domain.Entities.Church", null)
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roles_churches_church_id");
                });

            modelBuilder.Entity("Penuel.Domain.Entities.Services.ServiceAttendance", b =>
                {
                    b.HasOne("Penuel.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_attendances_persons_person_id");

                    b.HasOne("Penuel.Domain.Entities.Services.ServiceSession", "ServiceSession")
                        .WithMany()
                        .HasForeignKey("ServiceSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_attendances_service_sessions_service_session_id");

                    b.HasOne("Penuel.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_service_attendances_persons_updated_by_person_id");

                    b.Navigation("Person");

                    b.Navigation("ServiceSession");
                });

            modelBuilder.Entity("Penuel.Domain.Entities.Services.ServiceSession", b =>
                {
                    b.HasOne("Penuel.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("CreatedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_sessions_persons_created_by_person_id");

                    b.HasOne("Penuel.Domain.Entities.Person", "Preacher")
                        .WithMany()
                        .HasForeignKey("PreacherPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_service_sessions_persons_preacher_person_id");

                    b.HasOne("Penuel.Domain.Entities.Services.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_sessions_service_types_service_type_id");

                    b.HasOne("Penuel.Domain.Entities.Society", "Society")
                        .WithMany()
                        .HasForeignKey("SocietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_service_sessions_societies_society_id");

                    b.HasOne("Penuel.Domain.Entities.Person", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_service_sessions_persons_teacher_person_id");

                    b.HasOne("Penuel.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_service_sessions_persons_updated_by_person_id");

                    b.Navigation("Preacher");

                    b.Navigation("ServiceType");

                    b.Navigation("Society");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Penuel.Domain.Entities.Services.ServiceType", b =>
                {
                    b.HasOne("Penuel.Domain.Entities.Church", null)
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_types_churches_church_id");
                });

            modelBuilder.Entity("Penuel.Domain.Entities.Services.SundaySchoolTeachingAssignment", b =>
                {
                    b.HasOne("Penuel.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("AssignedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sunday_school_teaching_assignments_persons_assigned_by_pers");

                    b.HasOne("Penuel.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sunday_school_teaching_assignments_persons_person_id");

                    b.HasOne("Penuel.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("RevokedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sunday_school_teaching_assignments_persons_revoked_by_perso");

                    b.HasOne("Penuel.Domain.Entities.Society", "Society")
                        .WithMany()
                        .HasForeignKey("SocietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sunday_school_teaching_assignments_societies_society_id");

                    b.Navigation("Person");

                    b.Navigation("Society");
                });

            modelBuilder.Entity("Penuel.Domain.Entities.Services.TitheEntry", b =>
                {
                    b.HasOne("Penuel.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("CreatedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tithe_entries_persons_created_by_person_id");

                    b.HasOne("Penuel.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tithe_entries_persons_person_id");

                    b.HasOne("Penuel.Domain.Entities.Services.ServiceSession", "ServiceSession")
                        .WithMany()
                        .HasForeignKey("ServiceSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tithe_entries_service_sessions_service_session_id");

                    b.HasOne("Penuel.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tithe_entries_persons_updated_by_person_id");

                    b.Navigation("Person");

                    b.Navigation("ServiceSession");
                });

            modelBuilder.Entity("Penuel.Domain.Entities.Society", b =>
                {
                    b.HasOne("Penuel.Domain.Entities.Church", null)
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_societies_churches_church_id");
                });

            modelBuilder.Entity("Penuel.Domain.Entities.SocietyLeadership", b =>
                {
                    b.HasOne("Penuel.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("AssignedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_society_leaderships_persons_assigned_by_person_id");

                    b.HasOne("Penuel.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_society_leaderships_persons_person_id");

                    b.HasOne("Penuel.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("RevokedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_society_leaderships_persons_revoked_by_person_id");

                    b.HasOne("Penuel.Domain.Entities.Society", "Society")
                        .WithMany()
                        .HasForeignKey("SocietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_society_leaderships_societies_society_id");

                    b.Navigation("Person");

                    b.Navigation("Society");
                });

            modelBuilder.Entity("Penuel.Domain.Entities.SocietyMembership", b =>
                {
                    b.HasOne("Penuel.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("AssignedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_society_memberships_persons_assigned_by_person_id");

                    b.HasOne("Penuel.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_society_memberships_persons_person_id");

                    b.HasOne("Penuel.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("RevokedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_society_memberships_persons_revoked_by_person_id");

                    b.HasOne("Penuel.Domain.Entities.Society", "Society")
                        .WithMany()
                        .HasForeignKey("SocietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_society_memberships_societies_society_id");

                    b.Navigation("Person");

                    b.Navigation("Society");
                });

            modelBuilder.Entity("Penuel.Domain.Entities.UserAccount", b =>
                {
                    b.HasOne("Penuel.Domain.Entities.Person", "Person")
                        .WithOne()
                        .HasForeignKey("Penuel.Domain.Entities.UserAccount", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_accounts_persons_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Penuel.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Penuel.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("AssignedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_roles_persons_assigned_by_person_id");

                    b.HasOne("Penuel.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("RevokedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_roles_persons_revoked_by_person_id");

                    b.HasOne("Penuel.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Penuel.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_user_accounts_user_account_id");

                    b.Navigation("Role");

                    b.Navigation("UserAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
